### ISSUE TITLE
new pynvm release

### ISSUE THREAD

**Issue by bitdancer** [pmem/pynvm#13]
Once "enough" features are implemented (which I would say would be the default serializer/whitelist, support for PersitentObject, and the expanded docs), we should cut a new pynvm release and upload it to pypi.  We will need perone's help with that, as I presume he is the current owner of the pypi project.

**Comment by catalin-manciu** [comment]
Version 3.1 released and uploaded to [PyPI](https://pypi.python.org/pypi/pynvm)
