### ISSUE TITLE
Add support for PersistentTuples.

### ISSUE THREAD

**Issue by bitdancer** [pmem/pynvm#9]
From our point of view tuples are an immutable list, so the code should be a stripped down version of the PersistentList code.  This is worth adding as a Persistent class so that we aren't going through a pickle/unpickle serialization for the whole tuple.

**Comment by catalin-manciu** [comment]
Added in [2e35b82b8349718f1fc111a7464aae30198f254f](https://github.com/pmem/pynvm/commit/2e35b82b8349718f1fc111a7464aae30198f254f)
